services:
  ghost:
    image: ghost:5.9-alpine
    container_name: ghost
    restart: on-failure
    ports:
      - "3001:2368"
    environment:
      - url=http://${HOST}
      - mail__transport=SMTP
      - mail__from=${MAIL_FROM}
      - mail__options__host=${MAIL_HOST}
      - mail__options__port=${MAIL_PORT}
      - mail__options__secure=true
      - mail__options__auth__user=${MAIL_USER}
      - mail__options__auth__pass=${MAIL_PASS}
      - database__client=sqlite3
      - database__connection__filename=/var/lib/ghost/content/data/ghost.db
    volumes:
      - ghost-data:/var/lib/ghost/content
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 5
      test: timeout 3 bash -c '</dev/tcp/ghost/2368'

volumes:
  ghost-data:
    driver: local
